### ISSUE TITLE
MX switches

### ISSUE THREAD

**Issue by the-argus** [pashutk/chocofi#11]
The board in the images folder looks like it works both with mx and choco switches, though I can't quite tell. A friend of mine ordered the board for me, and is 3D printing the chassis, so I don't know much about the build. I just would like to know if mx switches will fit in the board. I know the fifi exists but its nice to have the option.

**Comment by pashutk** [comment]
Hi @the-argus!
Unfortunately, MX switches wouldn't fit, it's a choc-only board. And it's basically Fifi board tuned for chocs specifically, so yeah, if you want MX you go with Fifi, and for chocs there's Chocofi.

**Comment by the-argus** [comment]
thanks for the clarification!
