### ISSUE TITLE
Please share step files for case top and bottom

### ISSUE THREAD

**Issue by pfn** [pashutk/chocofi#3]
Hi @pashutk chocofi is great, and I'm currently using it now, I'm looking at encasing it, and want to make some mods to the case, like for a power switch, could you share the step files so that it would be easier to make modifications, please? Thank you!

**Comment by pashutk** [comment]
Hi @pfn, glad you like it!

I've added step files in case folder, please check https://github.com/pashutk/chocofi/tree/main/case/v1. Please let me know if this won't work.

**Comment by pfn** [comment]
This looks great, imports OK  and I should be able to use this to make my edits. Thank you!
